# Generated by Django 3.2.13 on 2022-07-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20220726_2234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
